# Generated by Django 6.0.3 on 2026-03-26 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('classificacao_financeira', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_entrega_mpm', models.CharField(blank=True, max_length=100, null=True)),
                ('contato_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['razao_social', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='StatusSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos_salvos', to='core.cliente')),
            ],
            options={
                'ordering': ['nome_contato', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='core.empresa'),
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nf_sistema', models.CharField(blank=True, max_length=50, null=True)),
                ('serie_nf', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_nf', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('vendedor_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('vendedor_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('transportadora_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('transportadora_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cfop', models.CharField(blank=True, max_length=20, null=True)),
                ('cfop_descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('frete_ctr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('frete_nf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('seguro', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('difal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fcp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('iss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lucro_reais', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lucro_percentual', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='core.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='core.empresa')),
            ],
            options={
                'ordering': ['-data_emissao', '-numero_nf', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prnf', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_item', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('valor_total_item', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('custo_n', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_icms', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_pis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_irpj', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_csll', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_est_ircs_ou_simples', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_icmsst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_pisst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('v_cofinsst', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fcp_st', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('agrp', models.CharField(blank=True, max_length=100, null=True)),
                ('faixa_desconto', models.CharField(blank=True, max_length=100, null=True)),
                ('al_cred_simp', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('al_csll', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('al_irpj', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.notafiscal')),
            ],
            options={
                'ordering': ['descricao_item', 'item', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RastreioNotaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=50)),
                ('codigo_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('serial_lote', models.CharField(blank=True, max_length=255, null=True)),
                ('saidas_raw', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_doc', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rastreios_importados', to='core.empresa')),
            ],
            options={
                'ordering': ['numero_nf', 'codigo_produto', 'serial_lote'],
            },
        ),
        migrations.CreateModel(
            name='SAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('ano', models.PositiveIntegerField(default=0)),
                ('sequencia_ano', models.PositiveIntegerField(default=0)),
                ('contato_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_1', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone_2', models.CharField(blank=True, max_length=30, null=True)),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_usuario_contato', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa_usuario_contato', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_usuario_contato', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp_usuario_contato', models.CharField(blank=True, max_length=30, null=True)),
                ('email_usuario_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('cidade_usuario_contato', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_usuario_contato', models.CharField(blank=True, max_length=2, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status_inicial', models.CharField(default='Aberto', max_length=30)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.notafiscal')),
                ('usuario_abertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('setor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.setor')),
            ],
            options={
                'ordering': ['-data_abertura', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SACAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='sac_anexos/')),
                ('sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sac')),
            ],
        ),
        migrations.CreateModel(
            name='SACItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rastreio', models.CharField(choices=[('LOTE', 'Lote'), ('SERIAL', 'Serial')], max_length=10)),
                ('numero_rastreio', models.CharField(blank=True, max_length=150, null=True)),
                ('quantidade_com_problema', models.PositiveIntegerField(default=1)),
                ('observacao_item', models.TextField(blank=True, null=True)),
                ('item_nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.itemnotafiscal')),
                ('sac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_sac', to='core.sac')),
                ('tipo_ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipoocorrencia')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.setor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_interno'), name='uq_cliente_empresa_codigo_interno'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_nf'), name='uq_notafiscal_empresa_numero'),
        ),
        migrations.AddConstraint(
            model_name='itemnotafiscal',
            constraint=models.UniqueConstraint(fields=('nota_fiscal', 'codigo_produto', 'descricao_item'), name='uq_item_nf_codigo_descricao'),
        ),
        migrations.AddConstraint(
            model_name='rastreionotaitem',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_nf', 'codigo_produto', 'serial_lote'), name='uq_rastreio_nf_item_serial'),
        ),
        migrations.AddConstraint(
            model_name='sacitem',
            constraint=models.UniqueConstraint(fields=('item_nota_fiscal', 'tipo_rastreio', 'numero_rastreio'), name='uq_sacitem_item_rastreio'),
        ),
    ]
