# Generated by Django 6.0.3 on 2026-04-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_sacitem_uq_sacitem_item_rastreio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturezaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Natureza da Operação',
                'verbose_name_plural': 'Naturezas da Operação',
                'ordering': ['nome'],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'uq_sacitem_item_rastreio'
                ) THEN
                    ALTER TABLE core_sacitem
                    DROP CONSTRAINT uq_sacitem_item_rastreio;
                END IF;
            END
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
