# Generated by Django 6.0.3 on 2026-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20260404_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={},
        ),
        migrations.AlterField(
            model_name='sacitem',
            name='grupo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sacitem',
            name='item_quebrado_inservivel',
            field=models.CharField(
                blank=True,
                choices=[('SIM', 'Sim'), ('NAO', 'Não')],
                max_length=3,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='setor',
            name='codigo',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
