# Generated by Django 6.0.4 on 2026-05-06 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_retificar_sac_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoLegadoSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo_origem', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRY_RUN', 'Simulacao'), ('COMMIT', 'Importado'), ('ERRO', 'Erro')], default='DRY_RUN', max_length=20)),
                ('dry_run', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('total_sacs_planilha', models.PositiveIntegerField(default=0)),
                ('sacs_criados', models.PositiveIntegerField(default=0)),
                ('sacs_atualizados', models.PositiveIntegerField(default=0)),
                ('itens_criados', models.PositiveIntegerField(default=0)),
                ('itens_atualizados', models.PositiveIntegerField(default=0)),
                ('itens_ignorados', models.PositiveIntegerField(default=0)),
                ('sacs_pulados', models.PositiveIntegerField(default=0)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importacao Legado SAC',
                'verbose_name_plural': 'Importacoes Legado SAC',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
