# Generated by Django 6.0.4 on 2026-05-09 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_metadados_referencia_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoCadastroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('empresas', 'Empresas'), ('setores', 'Setores'), ('acoes_em_espera', 'Acoes em espera'), ('usuarios', 'Usuarios'), ('status_sac', 'Status do SAC'), ('tipos_ocorrencia', 'Tipos de ocorrencia'), ('clientes', 'Clientes'), ('contatos_clientes', 'Contatos dos clientes'), ('notas_fiscais', 'Notas fiscais'), ('itens_notas_fiscais', 'Itens das notas fiscais'), ('rastreios', 'Rastreios / Seriais'), ('tratativas_problema', 'Tratativas do problema'), ('tipos_problema', 'Tipos de problema'), ('tecnicos_externos', 'Tecnicos externos'), ('tabela_pecas', 'Tabela de pecas'), ('sacs', 'SACs'), ('itens_sac', 'Itens do SAC'), ('anexos_sac', 'Anexos do SAC'), ('historicos_sac', 'Historicos do SAC'), ('importacoes_legado', 'Importacoes legado'), ('analises_tecnicas', 'Analises tecnicas'), ('orcamentos_tecnicos', 'Orcamentos tecnicos'), ('pecas_orcamento', 'Pecas do orcamento'), ('naturezas_operacao', 'Naturezas de operacao'), ('fluxo_acoes', 'Fluxo de acoes'), ('vendedores', 'Vendedores')], max_length=80)),
                ('nivel', models.CharField(choices=[('alterar', 'Incluir/Alterar'), ('visualizar', 'Visualizar'), ('sem_acesso', 'Sem Acesso')], default='sem_acesso', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_cadastros_simples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PermissÃ£o de item do cadastro',
                'verbose_name_plural': 'PermissÃµes de itens do cadastro',
                'ordering': ['item'],
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='PermissaoTelaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tela', models.CharField(choices=[('painel', 'Painel principal'), ('abertura_sac', 'Abrir novo SAC'), ('pesquisa_sacs', 'Consultar SACs'), ('dashboard_sla', 'Dashboard SLA'), ('gestao_sac', 'Gestao do SAC'), ('gestao_comercial', 'Gestao Comercial'), ('gestao_logistica', 'Gestao Logistica'), ('gestao_licitacao', 'Gestao Licitacao'), ('assessoria_cientifica', 'Assessoria Cientifica'), ('assistencia_tecnica', 'Assistencia Tecnica'), ('gestao_financeira', 'Gestao Financeira'), ('diretoria', 'Diretoria'), ('importacoes', 'Importacoes'), ('cadastros', 'Cadastros'), ('retificar_sac', 'Retificar SAC')], max_length=80)),
                ('nivel', models.CharField(choices=[('alterar', 'Incluir/Alterar'), ('visualizar', 'Visualizar'), ('sem_acesso', 'Sem Acesso')], default='sem_acesso', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_telas_simples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PermissÃ£o por tela',
                'verbose_name_plural': 'PermissÃµes por tela',
                'ordering': ['tela'],
                'unique_together': {('user', 'tela')},
            },
        ),
    ]
