# Generated by Django 6.0.4 on 2026-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_permissaocadastrousuario_permissaotelausuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosistema',
            options={'ordering': ['nome_completo'], 'permissions': [('acessar_painel', 'Pode acessar Painel / Intra'), ('acessar_dashboard_sla', 'Pode acessar Dashboard SLA'), ('acessar_pesquisa_sacs', 'Pode acessar Pesquisa de SACs'), ('acessar_abertura_sac', 'Pode acessar Abertura de SAC'), ('acessar_comercial', 'Pode acessar Análise Comercial'), ('acessar_logistica', 'Pode acessar Gestão Logística'), ('acessar_assessoria', 'Pode acessar Assessoria Científica'), ('acessar_assistencia_tecnica', 'Pode acessar Assistência Técnica'), ('acessar_diretoria', 'Pode acessar Diretoria'), ('acessar_financeiro', 'Pode acessar Gestão Financeira'), ('acessar_licitacao', 'Pode acessar Gestão Licitação'), ('acessar_importacoes', 'Pode acessar Importações'), ('acessar_admin_cadastros', 'Pode acessar Cadastros / Admin'), ('retificar_sac', 'Pode retificar dados de abertura do SAC'), ('cancelar_sac', 'Pode cancelar SAC')]},
        ),
        migrations.AlterField(
            model_name='permissaotelausuario',
            name='tela',
            field=models.CharField(choices=[('painel', 'Painel principal'), ('abertura_sac', 'Abrir novo SAC'), ('pesquisa_sacs', 'Consultar SACs'), ('dashboard_sla', 'Dashboard SLA'), ('gestao_sac', 'Gestao do SAC'), ('gestao_comercial', 'Gestao Comercial'), ('gestao_logistica', 'Gestao Logistica'), ('gestao_licitacao', 'Gestao Licitacao'), ('assessoria_cientifica', 'Assessoria Cientifica'), ('assistencia_tecnica', 'Assistencia Tecnica'), ('gestao_financeira', 'Gestao Financeira'), ('diretoria', 'Diretoria'), ('importacoes', 'Importacoes'), ('cadastros', 'Cadastros'), ('retificar_sac', 'Retificar SAC'), ('cancelar_sac', 'Cancelar SAC')], max_length=80),
        ),
    ]
