# Generated by Django 6.0.3 on 2026-03-27 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoEmEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ação em Espera',
                'verbose_name_plural': 'Ações em Espera',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipoocorrencia',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Ocorrência', 'verbose_name_plural': 'Tipos de Ocorrência'},
        ),
        migrations.AddField(
            model_name='tipoocorrencia',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.setor'),
        ),
        migrations.AddField(
            model_name='sac',
            name='acao_em_espera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sacs', to='core.acaoemespera'),
        ),
        migrations.AddField(
            model_name='tipoocorrencia',
            name='acao_em_espera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_ocorrencia', to='core.acaoemespera'),
        ),
    ]
