# Generated by Django 6.0.3 on 2026-04-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_naturezaoperacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacitem',
            name='natureza_operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_sac', to='core.naturezaoperacao'),
        ),
    ]
