# Generated by Django 6.0.3 on 2026-04-03 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sacitem_natureza_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoAcaoSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('acao_atual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_origem', to='core.acaoemespera')),
                ('proxima_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_destino', to='core.acaoemespera')),
                ('proximo_setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_setor_destino', to='core.setor')),
                ('setor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.setor')),
            ],
        ),
    ]
