# Generated by Django 6.0.3 on 2026-04-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pecatabelapreco_grupo_custo'),
        ('core', '0016_sacitem_grupo_item_quebrado_inservivel'),
        ('core', '0020_fluxoacaosetor'),
    ]

    operations = [
    ]
