# Generated by Django 6.0.3 on 2026-04-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_setor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxoacaosetor',
            options={'ordering': ['acao_atual__nome', 'setor_atual__nome', 'proxima_acao__nome'], 'verbose_name': 'Fluxo Ação/Setor', 'verbose_name_plural': 'Fluxos Ação/Setor'},
        ),
        
        migrations.RemoveField(
            model_name='setor',
            name='codigo',
        ),
    ]
