# Generated by Django 6.0.3 on 2026-04-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fix_email_nullable_definitivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacanalisecomercial',
            name='valor_desconto_pleiteado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoacaosetor',
            name='status_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fluxos_como_status_destino', to='core.statussac'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
