# Generated by Django 6.0.3 on 2026-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_travar_codigo_statussac'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'uq_sacitem_item_rastreio'
                        ) THEN
                            ALTER TABLE core_sacitem
                            DROP CONSTRAINT uq_sacitem_item_rastreio;
                        END IF;
                    END
                    $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='sacitem',
                    name='uq_sacitem_item_rastreio',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='setor',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
