# Generated by Django 6.0.3 on 2026-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_sachistorico_arquivo_tecnicoexterno_arquivo'),
        ('core', '0037_sachistorico_arquivo_fix'),
    ]

    operations = [
    ]
